name: Get Epic Game

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-11
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: compile
        run: |
         make 

