name: Test build for m1 on GitHub

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: |
         make 

      - name: Upload for test on m1 machine
        uses: actions/upload-artifact@v2
        with:
          name: test-me-on-m1
          path: test

